### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [Daizhen1995/request-fullscreen-js#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by Daizhen1995** [comment]
You are extremely welcome.


 原始邮件 
发件人: George Pickering<notifications@github.com>
收件人: Daizhen1995/request-fullscreen-js<request-fullscreen-js@noreply.github.com>
抄送: Subscribed<subscribed@noreply.github.com>
发送时间: 2020年11月15日(周日) 06:24
主题: [Daizhen1995/request-fullscreen-js] TypeScript type declaration file(#1)


If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by geopic** [comment]
Great, I'll get started on it now.
